version: "3"
services:
  dev:
    build: .
    image: maximzasorin/highloadcup-2
    ports:
      - "3000:80"
    volumes:
     - ~/highload/testing/data:/tmp/data
  full:
    build: .
    image: maximzasorin/highloadcup-2
    ports:
      - "3000:80"
    volumes:
     - ~/highload/full/data:/tmp/data